pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'cd major;mvn dockerfile:build'
                sh 'cd manager;mvn dockerfile:build'
            }
        }
        stage('Deliver') {
            agent {label 'slave'}
            steps {
                sh 'ls /usr/bin'
                sh 'pwd'
            }
        }
    }
}
